name: CI
on:
  push:
    branches: [main, master]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            ccache \
            clang \
            glslang-tools \
            libvulkan-dev \
            libx11-dev \
            libxi-dev \
            libwayland-dev \
            libxkbcommon-dev \
            meson \
            ninja-build \
            pkg-config \
            spirv-headers \
            wayland-protocols

      - name: Configure
        run: CC='ccache clang' CXX='ccache clang++' meson setup --buildtype=release --prefix=/usr build

      - name: Compile
        run: meson compile -C build
